# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# testing

name: Create and build image and deploy using helm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  repo: lwplapbs
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest


    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: run build and copy the jar files to build context
        run: ./build-app.sh
           
      - name: Build and push front image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: app/front/src/main/docker/
          push: true
          tags: lwplapbs/front:latest

      - name: Build and push back image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: app/back/src/main/docker/
          push: true
          tags: lwplapbs/back:latest

      - name: Build and push reader image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: app/reader/src/main/docker/
          push: true
          tags: lwplapbs/reader:latest

      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install front-app ./springboot -f front-values.yaml
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'

      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install back-app ./springboot -f back-values.yaml
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'

      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install reader-app ./springboot -f reader-values.yaml
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'

